results_dir = "/home/kristen/BetterFaster3.1/betterFaster/sim_utils/fake_data" 
isCarla = false
skip_writing_files = false 
experiments = 10 
sim_length = 500 

[betterTogether]
P_Miss_detection = 0.1 
P_False_detection = 0.05 
lambda_u = 0.003 
detection_threshold = 0.9 
rejection_threshold = 0.5 
min_feats = 3 
max_feats = 100 
sensor_noise_variance = 0.1
confidence_range = 25 
miss_detection_probability_parameters = [-0.000002,0.0025]

[betterFaster]
data_association_rates = [0.3,0.6,0.9]
T_nu_cone = 9 
T_nu_tree = 3
growth_state_relevancy_level = 0.75 
n_gstates = 3 
hamming_distance_similarity = 0.9

[slam]
n_particles = 25
localization_covariance_params = [0.04,0.04,0.25]
[vehicle_parameters]
img_width = 1392 
img_height = 1024 
fov = 72 

[comparison_bools]
compare_betterTogether = false  
compare_vanilla = false 
compare_multiMap = false 